"""Generate docs/TOOLS.md (tool reference + capability matrix) from the live tool registry.

Run:  python scripts/gen_tool_docs.py
CI can run it with --check to fail when the committed docs are stale.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "TOOLS.md"

CAPABILITY = {
    "identity": "Identity & workspace",
    "sql": "SQL & data exploration",
    "compute": "Compute",
    "workspace": "Code & workspace",
    "jobs": "Jobs",
    "pipelines": "Spark Declarative Pipelines",
    "unity_catalog": "Unity Catalog",
    "volumes": "Volumes & files",
    "dashboards": "AI/BI dashboards",
    "ai": "AI: serving, agents, Genie",
    "vector_search": "Vector Search",
    "lakebase": "Lakebase (Postgres)",
    "apps": "Databricks Apps",
    "manifest": "Project manifest",
    "pdf": "PDF generation",
}


def _mark(flag: bool) -> str:
    return "✓" if flag else ""


async def render() -> str:
    for key in list(os.environ):
        if key.startswith("DBX_MCP_"):
            del os.environ[key]
    os.environ["DBX_MCP_MANIFEST_PATH"] = str(ROOT / ".databricks_mcp" / "_docs_manifest.json")
    from dbx_mcp.databricks.client import ClientProvider
    from dbx_mcp.safety.levels import SafetyLevel
    from dbx_mcp.server.app import build_server
    from dbx_mcp.server.config import Settings

    settings = Settings.from_env()
    server, specs = build_server(settings, ClientProvider(settings, factory=lambda s, p: MagicMock()))
    tools = {t.name: t for t in await server.list_tools()}

    lines = [
        "# Tool reference",
        "",
        "> Generated by `scripts/gen_tool_docs.py` from the tool registry. Do not edit by hand.",
        "",
        f"{len(specs)} tools across {len({s.toolset for s in specs})} toolsets. Every tool returns the common "
        "envelope (`status`, `summary`, `data`, `page`, `plan`, `warnings`, `next_steps`, `request_id`).",
        "",
        "## Capability matrix",
        "",
        "| Capability | MCP Tool | Read | Write | Destructive | Execution | Security Sensitive |",
        "|------------|----------|------|-------|-------------|-----------|--------------------|",
    ]
    for spec in specs:
        lv = spec.possible_levels
        lines.append(
            f"| {CAPABILITY.get(spec.toolset, spec.toolset)} | `{spec.name}` | {_mark(SafetyLevel.READ_ONLY in lv)} | "
            f"{_mark(SafetyLevel.WRITE in lv)} | {_mark(SafetyLevel.DESTRUCTIVE in lv)} | "
            f"{_mark(SafetyLevel.EXECUTION in lv)} | {_mark(SafetyLevel.SECURITY_SENSITIVE in lv)} |"
        )
    lines += ["", "Toolset names (for `DBX_MCP_TOOLSETS`): " + ", ".join(f"`{t}`" for t in CAPABILITY), ""]

    current = None
    for spec in specs:
        if spec.toolset != current:
            current = spec.toolset
            lines += [f"## {CAPABILITY.get(current, current)} (`{current}`)", ""]
        tool = tools[spec.name]
        lines += [f"### `{spec.name}`", "", spec.description, "", f"**Safety:** {spec.safety_summary()}", ""]
        props = tool.input_schema.get("properties", {})
        required = set(tool.input_schema.get("required", []))
        if props:
            lines += ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
            for name, schema in props.items():
                lines.append(
                    f"| `{name}` | {_type(schema)} | {'yes' if name in required else ''} | "
                    f"{_escape(schema.get('description', ''))} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _type(schema: dict) -> str:
    if "enum" in schema:
        return " \\| ".join(f"`{v}`" for v in schema["enum"])
    if "anyOf" in schema:
        return " \\| ".join(_type(s) for s in schema["anyOf"] if s.get("type") != "null") or "any"
    t = schema.get("type", "any")
    if t == "array":
        return f"array of {_type(schema.get('items', {}))}"
    return t


def _escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sys.path.insert(0, str(ROOT / "src"))
    text = asyncio.run(render())
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("docs/TOOLS.md is stale; run python scripts/gen_tool_docs.py", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
